### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'inProgress')

### ISSUE THREAD

**Issue by dibollinger** [Fredilein/CookieAudit#2]
```
background.js:23 Upgraded the CookieDB.
background.js:28 Successfully connected to CookieDB.
popup.html:50 Error handling response: TypeError: Cannot read properties of undefined (reading 'inProgress')
    at chrome-extension://iccfgkebifjbhlilcfdlbfabiakofdam/popup/popup.js:236:16
```
Occurs when clicking on the `Start Scan` button.

It seems like the code is trying to access the `"scan"` object in local storage before it was created there. Because the result is undefined, the code crashes when trying to access a property of it.

**Comment by Fredilein** [comment]
Thank you! This should be fixed now.

Commit: 6bbdbd6d55395e562fc0ab132edb0314c0837f49
